name: whether_the_weather_dev
services:
  app:
    image: ${PROJECT_NAME}:dev
    tty: true
    init: true
    links:
      - "db"
      # - "redis"
    expose:
      - 3000
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - db
      # - redis
  db:
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    volumes: 
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_USER}
    ports:
      - 127.0.0.1:5432:5432
  # redis:
  #   image: redis:latest
  #   container_name: ${REDIS_CONTAINER_NAME}

volumes:
  whether_the_weather_db:
